name: inheritance-dart-example
version: 1.2.3
description: >-
  This file has an example of inheritance concept using Dart programming language.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  efts: ^2.0.4
  transmogrify: ^0.4.0
dev_dependencies:
  test: '>=0.6.0 <0.12.0'
